### ISSUE TITLE
Error installing/loading extension 'chios' 

### ISSUE THREAD

**Issue by Edahi** [kallimachos/chios#5]
Dear `chios` editors. 

It is required an small update to the code to be functional with most recent versions of Sphinx:

> AttributeError: 'Sphinx' object has no attribute 'warn'
> The Sphinx.warn() method was deprecated at Sphinx-1.6 and removed at 1.8.
> So chios extension should be updated to use new sphinx.util.logging module.

[This is the discussion in Sphinx github addressing this issue](https://github.com/sphinx-doc/sphinx/issues/6760)

Thank you for such a required extension.

**Comment by kallimachos** [comment]
Thank you for the report, @Edahi. I'll have a look and aim to get a fix up soon.

**Comment by kallimachos** [comment]
@Edahi the fix is available in chios 0.1.5. Please let me know if you have any problems with it. Thanks!

**Comment by Edahi** [comment]
Just tested it. It works:
![Screen Shot 2019-11-07 at 11 11 35 AM](https://user-images.githubusercontent.com/22146178/68419600-65315f00-014f-11ea-9a1b-6103d63041f3.png)

Thank you.
